### ISSUE TITLE
Document the review mode feature

### ISSUE THREAD

**Issue by kossebau** [kogmbh/WebODF#686]
## TODO
* [x] document flag in the editor options of Wodo.TextEditor
* [x] add section to  `HOWTO-wodotexteditor.md` about it
* [x] polish `revieweditor.html` and `revieweditor.js` to be nice examples
* [x] add `revieweditor.html` and `revieweditor.js` to product zip file, mention in HOWTO
